- Dockerfile
- Jenkinsfile
- go.mod
Signed-off-by: Jacob Blain Christen <jacob.blain.christen@intel.com>
> add initial pipeline

- Dockerfile
- Jenkinsfile
- go.mod
- update Jenkinsfile to run tests during multi-stage build
- update go.mod file to depend on [`device-sdk-go@edinburgh`](https://github.com/edgexfoundry/device-sdk-go/tree/edinburgh)
Signed-off-by: Jacob Blain Christen <jacob.blain.christen@intel.com>
> bring in Jenkinsfile from master

- Jenkinsfile
Please do not merge this until after #14 is merged to `semver`
Signed-off-by: Jacob Blain Christen <jacob.blain.christen@intel.com>
> pipeline: bump pre instead of patch

- Jenkinsfile
Please do not merge until #14 is merged. These changes effectively match up with is what is in #15 
Signed-off-by: Jacob Blain Christen <jacob.blain.christen@intel.com>
> pipeline: bring in updated Jenkinsfile from edinburgh

- README.md
Updating title of readme and removing alpha text.
Removing references to Schedule and ScheduleEvents.
Adding references to AutoEvents.
Signed-off-by: xmlviking <ecotter@gmail.com>
> issue_1 updating readme.md removing scheduler references

- .gitignore
- Dockerfile
- Jenkinsfile
- Makefile
Signed-off-by: Tyler Powers <tyler.m.powers@intel.com>
> Add code coverage output

- go.mod
- internal/driver/snmpdriver.go
fix: #21 
Signed-off-by: Felix Ting <felix@iotechsys.com>
> Implement Device CUD callback in protocol driver

- cmd/res/configuration.toml
- cmd/res/docker/configuration.toml
- go.mod
Update go.mod according sdk change. Remove ReadMaxLimit from config. Enable remote logging at res/docker/configuration.toml .
Fix #26 #12
> Update sdk version and configuration.toml

- Attribution.txt
- Makefile
- bin/test-attribution-txt.sh
- bin/test-go-mod-tidy.sh
- cmd/main.go
- internal/driver/snmpclient_test.go
- internal/driver/snmpdriver.go
> Add Attribution file and extend maketest to check it

- go.mod
Fix #50 
Signed-off-by: Chris Hung <chris@iotechsys.com>
> upgrade sdk verion to v1.2.1 for geneva release

- Dockerfile
Signed-off-by: Koppolu <venkata.subbareddy.koppolu@intel.com>
What kind of change does this PR introduce?
Issue Number:
https://github.com/edgexfoundry/device-snmp-go/issues/57
> refactor: update dockerfile to appropriately use ENTRYPOINT and CMD, closes#57

- Dockerfile
- Dockerfile.build
- Jenkinsfile
- bin/test-attribution-txt.sh
- go.mod
fix #60 
Signed-off-by: Chris Hung <chris@iotechsys.com>
What kind of change does this PR introduce?
> build: Upgrade to Go1.15

- cmd/res/device.snmp.trendnet.TPE082WS.yaml
- profiles/device.snmp.patlite.yaml
- profiles/device.snmp.switch.dell.N1108P-ON.yaml
fixes #76
Signed-off-by: Jim White <jpwhite_mn@yahoo.com>
What kind of change does this PR introduce?
Issue Number: #76 
no behavior change.  Only updates to profiles to use Hanoi profile structures/terminology.
> fix: updated all example profiles to Hanoi profile structure

- Dockerfile
- Dockerfile.build
- go.mod
This PR updates the build of device-snmp-go to go 1.16.
- [NA] Tests for the changes have been added (for bug fixes / features)
- [NA] Docs have been added / updated (for bug fixes / features)
**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-snmp-go/blob/master/.github/CONTRIBUTING.md
- [ x] No
> fix(build): update to go 1.16

- .gitignore
- cmd/res/configuration.toml
- go.mod
**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-modbus-go/blob/master/.github/Contributing.md
Using DS specific SeviceInfo Struct with additional settings
Now using common SeviceInfo Struct
Moved non-common settings under `[Device]` section
BREAKING CHANGE: Service configuration has changed
> refactor: Update configuration for change to common ServiceInfo struct

- cmd/res/configuration.toml
- go.mod
- internal/driver/snmpdriver.go
**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-snmp-go/blob/master/.github/CONTRIBUTING.md
> refactor: bump dependency version and update import path

- GOVERNANCE.md
- OWNERS.md
- cmd/res/configuration.toml
- cmd/res/devices/device.snmp.trendnet.TPE082WS.toml
also added governance.md and owner.md files for LF Edge
Signed-off-by: jpwhitemn <jpwhite_mn@yahoo.com>
**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-snmp-go/blob/master/.github/CONTRIBUTING.md
> fix: update all TOML to use quote and not single-quote

- .github/workflows/snap.yaml
The workflow added here will activate only after it has been merged into the main. In the meantime, https://github.com/MonicaisHer/device-snmp-go/pull/1 that is against the fork can be taken as a reference.
Signed-off-by: Mengyi Wang <mengyi.wang@canonical.com>
> test: add snap CI workflow

- CHANGELOG.md
> docs: CHANGELOG fixup

- Makefile
- cmd/main.go
- version.go
fixes #172 for Jakarta
Signed-off-by: Leonard Goodell <leonard.goodell@intel.com>
> fix: (jakarta) Correctly set the versions for the service and sdk

- Dockerfile
- Makefile
- bin/test-attribution-txt.sh
- go.mod
- go.sum
- snap/local/hooks/go.mod
- snap/snapcraft.yaml
Signed-off-by: Leonard Goodell <leonard.goodell@intel.com>
run `make build test docker`
> build: Upgrade to Go 1.18 and optimize attribution script

- internal/driver/snmpdriver.go
> feat: Support reading multiple commands with a single request
